
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_salasanasi
      MYSQL_DATABASE: kokmet
      MYSQL_USER: metalliuser
      MYSQL_PASSWORD: käyttäjän_salasana
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./metalli67_dump.sql:/docker-entrypoint-initdb.d/metalli67_dump.sql:ro
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/.env:/app/.env
    environment:
      - NODE_ENV=production

  frontend:
    build: ./Frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
