version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/.env:/app/.env
    environment:
      - NODE_ENV=production

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
